### ISSUE TITLE
Playermodels are errors

### ISSUE THREAD

**Issue by kngrektor** [AndyBroski/Insplus#4]
Got it to "work" but some classes are missing playermodels. Theres "proper" collision on the erros, So im guessing its missing serversided. We have listed them here http://i.imgur.com/YK3MTq8.png
y = has model
x = no model

Got any idea why this is happening?

**Comment by AnSeph** [comment]
There was an update to the game a few days ago that changed playermodels. The old playermodels are no longer supported which is why you're getting the errors. I'm working on an update at the moment that will fix that. 

The new playermodels are classed by armor (the playermodels will change depending on armor equipped) and will add pouches and backpacks depending on the ammo rig equipped. I should be done with it by the end of the week.

**Comment by kngrektor** [comment]
Awesome :) Will the workshop version be updated then?
